repos:
-   repo: local
    hooks:
      - id: blue
        name: blue
        entry: bash -c 'blue .'
        language: system
        pass_filenames: false
        stages: [commit]
    hooks:
      - id: isort
        name: isort
        entry: bash -c 'isort .'
        language: system
        pass_filenames: false
        stages: [commit]