"""add fk grades to players

Revision ID: 2341bb52c168
Revises: a288c90cb135
Create Date: 2023-06-07 22:28:57.912251
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2341bb52c168'
down_revision = 'a288c90cb135'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('grade', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'grades', ['grade'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'grade')
    # ### end Alembic commands ###
