"""add autoincrement to player id for tests

Revision ID: 2944de044d9f
Revises: 5fdae641dd0f
Create Date: 2023-06-07 20:26:41.269074
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2944de044d9f'
down_revision = '5fdae641dd0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
