"""teste2

Revision ID: 5fdae641dd0f
Revises: 507e2504f298
Create Date: 2023-06-07 20:09:59.102687
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5fdae641dd0f'
down_revision = '507e2504f298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
