"""add grades table

Revision ID: a288c90cb135
Revises: f5654acb05a2
Create Date: 2023-06-07 22:25:59.632104
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a288c90cb135'
down_revision = 'f5654acb05a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'grades',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    # ### end Alembic commands ###
