"""add fk players-races

Revision ID: f5654acb05a2
Revises:
Create Date: 2023-06-07 22:20:40.003815
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f5654acb05a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'races',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'players',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('race', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['race'],
            ['races.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('races')
    # ### end Alembic commands ###
